{
 "title": "BANKVAULT",
 "description": "There must be some clear signal here\nSaid the trader to the quant\nThe data’s full of noise and fear\nThe patterns just aren’t what I want",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ticker",
    "label": "Ticker",
    "query": "select distinct ticker from tickers where category = '$Category';"
   },
   {
    "name": "Category",
    "label": "Category",
    "query": "select distinct category from tickers;"
   }
  ]
 },
 "panels": [
  {
   "title": "Candlestick for '$ticker'",
   "type": "candlestick",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", open, high, low, close, volume, ticker FROM stockticks WHERE ticker='$ticker' ORDER BY time"
    },
    {
     "rawSql": "SELECT \"timestamp\", close as \"Close\" FROM stockticks WHERE ticker='$ticker'"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ma_200::double precision AS ma_200\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\n  AND ma_200::numeric > 0.0\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "MACD $ticker",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  macd::double precision AS \"MACD\"\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\nORDER BY \"time\" ASC"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  macd_signal::double precision as \"MACD Signal\"\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\nORDER BY \"time\" ASC"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  macd::double precision - macd_signal::double precision AS \"Histogram Positive\"\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\n  AND macd::double precision - macd_signal::double precision > 0\nORDER BY \"time\" ASC"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  macd::double precision - macd_signal::double precision AS \"Histogram Negative\"\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\n  AND macd::double precision - macd_signal::double precision <= 0\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "$ticker RSI_14",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \n    \"timestamp\" AS \"time\", \n    rsi_14::double precision AS rsi_14\nFROM technicalfeatures \nWHERE rsi_14 IS NOT NULL\n  AND rsi_14::double precision > 0.0\n  AND ticker='$ticker'\nORDER BY \"timestamp\""
    }
   ]
  },
  {
   "title": "Moving Average 50_200 '$ticker'",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  close::double precision AS close\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\nORDER BY \"time\" ASC"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ma_200::double precision AS ma_200\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\n  AND ma_200::numeric > 0.0\nORDER BY \"time\" ASC"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ma_50::double precision AS ma_50\nFROM technicalfeatures \nWHERE ticker = '$ticker'\n  AND \"timestamp\" IS NOT NULL\n  AND ma_50::numeric > 0.0\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": " PORTFOLIO 20 Day Correlation Matrix ",
   "type": "table",
   "gridPos": { "h": 26, "w": 14, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \n  c.ticker_1,\n  c.ticker_2,\n  c.correlation\nFROM correlations as c\njoin tickers as t1\n  on c.ticker_1 = t1.ticker\njoin tickers as t2\n  on c.ticker_2 = t2.ticker\nwhere\n  t1.category = '$Category' and t2.category = '$Category';"
    }
   ]
  },
  {
   "title": "Watchlist Price Changes",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 43 },
   "targets": [
    {
     "rawSql": "WITH RecentClose AS (\n  SELECT\n    ticker,\n    close,\n    timestamp,\n    ROW_NUMBER() OVER (PARTITION BY ticker ORDER BY timestamp DESC) AS rn\n  FROM stockticks \n),\nLastUpdatedClose AS (\n  SELECT\n    t.ticker,\n    r.close AS last_updated_close,\n    ROW_NUMBER() OVER(PARTITION BY t.ticker ORDER BY r.timestamp DESC) AS rn\n  FROM tickers AS t\n  JOIN stockticks AS r\n    ON t.ticker = r.ticker\n  WHERE r.timestamp <= t.last_updated\n)\nSELECT\n  t.ticker as \"Ticker\",\n  t.last_updated as \"Date Added\",\n  luc.last_updated_close as \"Close at Date Added ($)\",\n  rc.close AS \"Most Recent Close ($)\",\n  ((rc.close - luc.last_updated_close) / luc.last_updated_close) * 100 AS \"Percentage Gain/Loss\"\nFROM tickers AS t\nJOIN RecentClose AS rc\n  ON t.ticker = rc.ticker\nJOIN LastUpdatedClose AS luc\n  ON t.ticker = luc.ticker\nWHERE\n  t.category = 'WATCHLIST'\n  AND rc.rn = 1\n  AND luc.rn = 1\norder by \"Percentage Gain/Loss\" desc;"
    }
   ]
  },
  {
   "title": "Tickers",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH base AS (\n    SELECT\n        ticker,\n        timestamp,\n        close,\n        LAG(close, 1) OVER (PARTITION BY ticker ORDER BY timestamp) AS prev_close_1d,\n        LAG(close, 5) OVER (PARTITION BY ticker ORDER BY timestamp) AS prev_close_1w,\n        LAG(close, 20) OVER (PARTITION BY ticker ORDER BY timestamp) AS prev_close_1m,\n        FIRST_VALUE(close) OVER (PARTITION BY ticker, date_trunc('year', timestamp) ORDER BY timestamp) AS first_close_ytd,\n        LAG(close, 252) OVER (PARTITION BY ticker ORDER BY timestamp) AS prev_close_1y\n    FROM stockticks \n),\nlatest AS (\n    SELECT\n        ticker,\n        MAX(timestamp) AS max_date\n    FROM stockticks \n    GROUP BY ticker\n)\nSELECT\n    b.ticker,\n    ROUND(((close - prev_close_1d) / prev_close_1d * 100)::numeric, 2) AS \"1 Day\",\n    ROUND(((close - prev_close_1w) / prev_close_1w * 100)::numeric, 2) AS \"1 Week\",\n    ROUND(((close - prev_close_1m) / prev_close_1m * 100)::numeric, 2) AS \"1 Month\",\n    ROUND(((close - first_close_ytd) / first_close_ytd * 100)::numeric, 2) AS \"YTD\",\n    ROUND(((close - prev_close_1y) / prev_close_1y * 100)::numeric, 2) AS \"1 Year\"\nFROM base b\nJOIN latest l\n  ON b.ticker = l.ticker AND b.timestamp = l.max_date\nORDER BY b.ticker;"
    }
   ]
  }
 ]
}