tickers:
  - VOOG
  - RKLB
  - SOFI
  - AAPL
  - NVDA
  - TSM
  - MSFT
  - GOOG
  - RDW
  - OSCR
  - GLD
  - META
  - AMZN
  - BRK.B
  - SCHD
  - NU
  - OKLO
  - SMR
  - SYM
  - OPEN
  - SMCI
  - TTD
  - PL
